apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
      - name: vprofile
        image: rupessh/vprofile4sep:latest
        ports:
        - containerPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: vprofile   # must match Deployment pod label
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8080 
  type: LoadBalancer

        
