name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven package
        run: mvn package

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

